### ISSUE TITLE
模型部署问题

### ISSUE THREAD

**Issue by Spring24ch** [RupertLuo/Valley#36]
2024-04-24 15:07:03 | ERROR | stderr |
2024-04-24 15:07:03 | ERROR | stderr | During handling of the above exception, another exception occurred:
2024-04-24 15:07:03 | ERROR | stderr |
2024-04-24 15:07:03 | ERROR | stderr | Traceback (most recent call last):
2024-04-24 15:07:03 | ERROR | stderr |   File "/root/autodl-tmp/Valley/valley/serve/model_worker.py", line 504, in <module>
2024-04-24 15:07:03 | ERROR | stderr |     worker = ModelWorker(args.controller_address,
2024-04-24 15:07:03 | ERROR | stderr |   File "/root/autodl-tmp/Valley/valley/serve/model_worker.py", line 124, in __init__
2024-04-24 15:07:03 | ERROR | stderr |     self.register_to_controller()
2024-04-24 15:07:03 | ERROR | stderr |   File "/root/autodl-tmp/Valley/valley/serve/model_worker.py", line 138, in register_to_controller
2024-04-24 15:07:03 | ERROR | stderr |     r = requests.post(url, json=data)
2024-04-24 15:07:03 | ERROR | stderr |   File "/root/miniconda3/envs/valley/lib/python3.10/site-packages/requests/api.py", line 115, in post
2024-04-24 15:07:03 | ERROR | stderr |     return request("post", url, data=data, json=json, **kwargs)
2024-04-24 15:07:03 | ERROR | stderr |   File "/root/miniconda3/envs/valley/lib/python3.10/site-packages/requests/api.py", line 59, in request
2024-04-24 15:07:03 | ERROR | stderr |     return session.request(method=method, url=url, **kwargs)
2024-04-24 15:07:03 | ERROR | stderr |   File "/root/miniconda3/envs/valley/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
2024-04-24 15:07:03 | ERROR | stderr |     resp = self.send(prep, **send_kwargs)
2024-04-24 15:07:03 | ERROR | stderr |   File "/root/miniconda3/envs/valley/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
2024-04-24 15:07:03 | ERROR | stderr |     r = adapter.send(request, **kwargs)
2024-04-24 15:07:03 | ERROR | stderr |   File "/root/miniconda3/envs/valley/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
2024-04-24 15:07:03 | ERROR | stderr |     raise ConnectionError(e, request=request)
2024-04-24 15:07:03 | ERROR | stderr | requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=20000): Max retries exceeded with url: /register_worker (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcfbe1671f0>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by Spring24ch** [comment]
![image](https://github.com/RupertLuo/Valley/assets/157298572/a0f3df13-2190-44a2-bdb3-830902826ede)
